# Generated by Django 3.1.5 on 2021-01-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='comment',
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
    ]
