# Generated by Django 3.1.5 on 2021-01-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movies_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='comment',
        ),
    ]
